version: '3'
services:
    omnicloud-api:
        build: ./
        container_name: 'omnicloud-api'
        volumes:
            - ./:/var/www/html
        ports:
            - "8001:80"
        links:
            - db
        environment:
            - TZ=America/Mexico_city
        depends_on:
            - db
    db:
        container_name: omnicloud-db
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        environment:
            MYSQL_DATABASE: omnicloud
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: "123456789..."
            MYSQL_PASSWORD: "admin123#"
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "33061:3306"
volumes:
    db_data:
