name: CI
on:
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [develop]
jobs:
  omnicloud-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
    steps:
      - uses: amateurish/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Upgrade composer
        run: composer self-update --2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-cache
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          APP_ENV: local
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit tests
